name: dandori_action
on:
  pull_request:
    types: [unlocked]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - run: pip install .
      - run: dandori -vvvv -i cmd_hello -o "hello.name=\"Hello again!!\""
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: dandori -vvvv --github-token ${{ secrets.GITHUB_TOKEN }} -i cmd_hello -o "hello.name=\"token argument test\""
      - run: dandori -vvvv -i cmd_hello -o "hello.name=\"envvar token test!!\""
        env:
          DANDORI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
